---
- name: Copy over the vagrant cart
  copy:
    src: files/vagrant
    dest: /export/stack/carts/
    mode: 0644

- name: Add the vagrant cart
  command: /opt/stack/bin/stack add cart vagrant

- name: Enable the vagrant cart
  command: /opt/stack/bin/stack enable cart vagrant
