---
- block:
    - name: Download CentOS-7-x86_64-Everything-1708.iso
      get_url:
        url: http://stacki-builds.labs.teradata.com/installer-isos/CentOS-7-x86_64-Everything-1708.iso
        dest: /export/isos/CentOS-7-x86_64-Everything-1708.iso
        checksum: "sha1:b9d9feace8d3b01527114f15eda5b29c64a7a60c"
        mode: 0644
    - name: Add Centos Pallet
      command: /opt/stack/bin/stack add pallet /export/isos/CentOS-7-x86_64-Everything-1708.iso
  when: ansible_distribution == "CentOS"

- name: Enable CentOS Pallet
  command: /opt/stack/bin/stack enable pallet CentOS
  when: ansible_distribution == "CentOS"

- block:
    - name: Download SLE-12-SP3-Server-DVD-x86_64-GM-DVD1.iso
      get_url:
        url: http://stacki-builds.labs.teradata.com/installer-isos/SLE-12-SP3-Server-DVD-x86_64-GM-DVD1.iso
        dest: /export/isos/SLE-12-SP3-Server-DVD-x86_64-GM-DVD1.iso
        checksum: "sha1:d5e880817ab39124d2be0a8f5e81498143067c10"
        mode: 0644
    - name: Add SLES Pallet
      command: /opt/stack/bin/stack add pallet /export/isos/SLE-12-SP3-Server-DVD-x86_64-GM-DVD1.iso
  when: ansible_distribution == "SLES"

- name: Enable Stacki SLES 12 Pallet
  command: /opt/stack/bin/stack enable pallet {{ ansible_distribution }} version=12
  when: ansible_distribution == "SLES"

- debug:
    msg: "{{ lookup('env','SLES_11_STACKI_ISO')|basename }}"

- name: Set sles_11 Variable
  set_fact:
    sles_11 : "{{ lookup('env','SLES_11_STACKI_ISO')|basename }}"

- name : SLES 11 setup
  include_tasks: sles11.yml
  when: '"-sles11.x86_64.disk1.iso" in sles_11'

- name: Create Minimal cart
  command: /opt/stack/bin/stack add cart Minimal
  when: ansible_distribution == "SLES"

- name: Create Minimal cart XML
  copy:
    dest: "/export/stack/carts/Minimal/nodes/cart-Minimal-backend.xml"
    content: |
      <stack:stack>
      <stack:description>
      minimal_sles11 cart backend appliance extensions
      </stack:description>
      <stack:package stack:meta="true">Minimal</stack:package>
      </stack:stack>
  when: ansible_distribution == "SLES"

- name: Enable Minimal cart on default box
  command: /opt/stack/bin/stack enable cart Minimal
  when: ansible_distribution == "SLES"