---
  - name: Copy Stacki ISO to frontend
    copy:
      src: "{{ lookup('env','STACKI_ISO') }}"
      dest: /export/isos/
      mode: 0644

  - name: Ensures vagrant dir exists
    file:
      path: /vagrant
      state: directory

  - name: Copy logo.png to use during rndc-confgen
    copy:
      src: "{{ item }}"
      dest: /vagrant/randomfile
      mode: 0644
    with_first_found:
        - "{{ lookup('env','TEST_FRAMEWORK_ROOT') }}/../logo.png"
        - "{{ lookup('env','TEST_FRAMEWORK_ROOT') }}/../stacki/logo.png" # For Jenkins
    when: lookup('env','GIT_BRANCH') is match("(feature|bugfix)/.*")

  - name: Setup /etc/host to a known good state
    copy:
      dest: /etc/hosts
      content: |
        127.0.0.1       localhost
        192.168.0.2     frontend-0-0  frontend-0-0
      mode: 0644

  - name: Copy frontend-install.py
    copy:
      src: "{{ item }}"
      dest: /root/
      mode: 0744
    with_first_found:
        - "{{ lookup('env','TEST_FRAMEWORK_ROOT') }}/../tools/fab/frontend-install.py"
        - "{{ lookup('env','TEST_FRAMEWORK_ROOT') }}/../stacki/tools/fab/frontend-install.py" # For Jenkins

  - name: Barnacle the frontend
    shell: /root/frontend-install.py --use-existing --stacki-iso=/export/isos/{{ lookup('env','STACKI_ISO')|basename }} <<< "2"
    register: barnacle_output

  - name: Barnacle Output
    echo:
      output: "{{ barnacle_output.stdout }}"
